/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AyWrIjrQ4rY
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 * Component has been modified to suite the project requirements.
 */

import Link from "next/link";
import CheckIcon from "../icons/CheckIcon";

export function Disaster() {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-background">
      <header className="lg:sticky lg:top-[82px] bg-transparent backdrop-blur-[20px] bg-[linear-gradient(120_deg,rgba(255,255,255,0.3),rgba(0,0,0,0.2))] px-4 lg:px-6 h-auto flex items-center justify-center border-b">
        <nav className="m-auto flex flex-col justify-center gap-4 sm:gap-6 md:flex-row">
          <Link
            href="#introduction"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Introduction
          </Link>
          <Link
            href="#jump-to-disaster"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Jump to Disaster
          </Link>
          <Link
            href="#types-of-disasters"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Types of Disasters
          </Link>
          <Link
            href="#disaster-response"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Disaster Response
          </Link>
          <Link
            href="#disaster-prevention"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Disaster Prevention
          </Link>
        </nav>
      </header>
      <main className="flex-1 px-4 lg:px-6 py-8 md:py-12 lg:py-16">
        <section id="introduction" className="mb-12 md:mb-16 lg:mb-20">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            Understanding Disasters and Their Impact
          </h1>
          <p className="mt-4 max-w-[700px] text-muted-foreground md:text-xl">
            Disasters, both natural and man-made, can have devastating
            consequences on individuals, communities, and entire regions.
            Understanding the different types of disasters, their causes, and
            the ways in which we can prepare for and respond to them is crucial
            for building a more resilient and sustainable future.
          </p>
        </section>
        <section id="jump-to-disaster" className="mb-12 md:mb-16 lg:mb-20">
          <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl">
            Jump to Disaster
          </h2>
          <div className="mt-4 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
            <Link
              href="/disasters/earthquake-info"
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}
            >
              Earthquakes
            </Link>
            <Link
              href="/disasters/flood-info"
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}
            >
              Floods
            </Link>
            <Link
              href="#"
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}
            >
              Wildfires
            </Link>
            {/* <Link
              href="#"
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}
            >
              Hurricanes
            </Link> */}
            <Link
              href="/disasters/typhoon-info"
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}
            >
              Typhoons
            </Link>
            <Link
              href="#"
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}
            >
              Industrial Accidents
            </Link>
            <Link
              href="#"
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}
            >
              Terrorist Attacks
            </Link>
            <Link
              href="#"
              className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}
            >
              Nuclear Accidents
            </Link>
          </div>
        </section>
        <section id="types-of-disasters" className="mb-12 md:mb-16 lg:mb-20">
          <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl">
            Types of Disasters
          </h2>
          <div className="mt-4 grid gap-8">
            <div>
              <h3 className="text-xl font-bold">Natural Disasters</h3>
              <p className="mt-2 text-muted-foreground">
                Natural disasters are events caused by natural processes of the
                Earth, such as earthquakes, floods, hurricanes, tornadoes,
                wildfires, and volcanic eruptions. These disasters can have
                devastating effects on communities, causing loss of life,
                destruction of property, and disruption of essential services.
              </p>
              <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <h4 className="text-lg font-bold">Earthquakes</h4>
                  <p className="mt-2 text-muted-foreground">
                    Earthquakes are sudden and violent shaking of the Earth&apos;s
                    surface, caused by the release of energy stored in the
                    Earth&apos;s crust or mantle. They can cause widespread damage to
                    buildings, infrastructure, and can trigger other disasters
                    like tsunamis.
                  </p>
                </div>
                <div>
                  <h4 className="text-lg font-bold">Floods</h4>
                  <p className="mt-2 text-muted-foreground">
                    Floods are the overflow of water onto land that is normally
                    dry. They can be caused by heavy rainfall, melting snow, or
                    the failure of dams or levees. Floods can damage buildings,
                    disrupt transportation, and contaminate water supplies.
                  </p>
                </div>
                <div>
                  <h4 className="text-lg font-bold">Wildfires</h4>
                  <p className="mt-2 text-muted-foreground">
                    Wildfires are uncontrolled fires that burn in natural
                    environments, such as forests, grasslands, and scrublands.
                    They can be caused by lightning, human activities, or other
                    natural phenomena, and can destroy homes, businesses, and
                    critical infrastructure.
                  </p>
                </div>
                <div>
                  <h4 className="text-lg font-bold">Typhoons</h4>
                  <p className="mt-2 text-muted-foreground">
                    Hurricanes are powerful tropical cyclones that form over
                    warm ocean waters. They can bring high winds, heavy
                    rainfall, storm surges, and tornadoes, causing widespread
                    damage to coastal and inland areas.
                  </p>
                </div>
              </div>
            </div>
            <div>
              <h3 className="text-xl font-bold">Man-Made Disasters</h3>
              <p className="mt-2 text-muted-foreground">
                Man-made disasters are events caused by human activities or
                decisions, such as industrial accidents, terrorist attacks, and
                nuclear accidents. These disasters can have severe consequences
                for both people and the environment.
              </p>
              <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <h4 className="text-lg font-bold">Industrial Accidents</h4>
                  <p className="mt-2 text-muted-foreground">
                    Industrial accidents are unintended events that occur in
                    industrial settings, such as factories, power plants, or
                    chemical facilities. These accidents can release toxic
                    substances, cause explosions, or lead to other catastrophic
                    events.
                  </p>
                </div>
                <div>
                  <h4 className="text-lg font-bold">Terrorist Attacks</h4>
                  <p className="mt-2 text-muted-foreground">
                    Terrorist attacks are intentional acts of violence or
                    destruction carried out by individuals or groups with
                    political, religious, or ideological motives. These attacks
                    can target civilians, infrastructure, or government
                    institutions, causing widespread fear and disruption.
                  </p>
                </div>
                <div>
                  <h4 className="text-lg font-bold">Nuclear Accidents</h4>
                  <p className="mt-2 text-muted-foreground">
                    Nuclear accidents are unintended events that occur in
                    nuclear power plants or facilities, resulting in the release
                    of radioactive materials into the environment. These
                    accidents can have long-lasting and devastating effects on
                    human health and the environment.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="disaster-response" className="mb-12 md:mb-16 lg:mb-20">
          <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl">
            Disaster Response
          </h2>
          <div className="mt-4 grid gap-8">
            <div>
              <h3 className="text-xl font-bold">Emergency Preparedness</h3>
              <p className="mt-2 text-muted-foreground">
                Preparing for disasters is crucial to minimize their impact and
                ensure the safety of individuals and communities. Emergency
                preparedness involves developing plans, stockpiling supplies,
                and practicing drills to be ready for when disasters strike.
              </p>
              <ul className="mt-4 grid gap-2 text-muted-foreground">
                <li>
                  <CheckIcon className="mr-2 inline-block h-4 w-4" />
                  Develop a family emergency plan and practice it regularly.
                </li>
                <li>
                  <CheckIcon className="mr-2 inline-block h-4 w-4" />
                  Assemble a disaster supply kit with essential items like food,
                  water, and first-aid supplies.
                </li>
                <li>
                  <CheckIcon className="mr-2 inline-block h-4 w-4" />
                  Stay informed about potential disasters and heed all warnings
                  and evacuation orders.
                </li>
              </ul>
            </div>
            <div>
              <h3 className="text-xl font-bold">Disaster Relief Efforts</h3>
              <p className="mt-2 text-muted-foreground">
                When disasters strike, a coordinated response from government
                agencies, non-profit organizations, and international aid groups
                is crucial for providing emergency assistance, restoring
                essential services, and supporting long-term recovery efforts.
              </p>
              <ul className="mt-4 grid gap-2 text-muted-foreground">
                <li>
                  <CheckIcon className="mr-2 inline-block h-4 w-4" />
                  Government agencies like NDRF and the Red Cross provide
                  disaster relief and coordinate recovery efforts.
                </li>
                <li>
                  <CheckIcon className="mr-2 inline-block h-4 w-4" />
                  Non-profit organizations(NGOs) offer humanitarian aid, shelter, and
                  other essential services to affected communities.
                </li>
                <li>
                  <CheckIcon className="mr-2 inline-block h-4 w-4" />
                  International aid organizations provide resources and
                  expertise to support disaster response and long-term
                  rebuilding.
                </li>
              </ul>
            </div>
          </div>
        </section>
        <section id="disaster-prevention" className="mb-12 md:mb-16 lg:mb-20">
          <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl">
            Disaster Prevention
          </h2>
          <div className="mt-4 grid gap-8">
            <div>
              <h3 className="text-xl font-bold">Early Warning Systems</h3>
              <p className="mt-2 text-muted-foreground">
                Early warning systems are critical for detecting and predicting
                the onset of disasters, allowing communities to take necessary
                precautions and minimize the impact of these events.
              </p>
              <ul className="mt-4 grid gap-2 text-muted-foreground">
                <li>
                  <CheckIcon className="mr-2 inline-block h-4 w-4" />
                  Seismic monitoring networks can detect and warn about
                  impending earthquakes.
                </li>
                <li>
                  <CheckIcon className="mr-2 inline-block h-4 w-4" />
                  Weather forecasting and satellite technology can track and
                  predict the path of hurricanes, tornadoes, and other severe
                  weather events.
                </li>
                <li>
                  <CheckIcon className="mr-2 inline-block h-4 w-4" />
                  Wildfire detection systems use sensors and satellite imagery
                  to identify and monitor the spread of wildfires.
                </li>
              </ul>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
