/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5MmQ0CPLDoA
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 * Component has been modified to tailor towards d-info project
 */

import Link from "next/link";
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
  TableBody,
  TableCell,
} from "@/components/ui/table";
import CheckIcon from "../icons/CheckIcon";

export function EarthquakeInfo() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-primary text-primary-foreground">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col-reverse justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-2xl font-bold tracking-tighter sm:text-5xl xl:text-5xl/none">
                    Preparing for Earthquakes
                  </h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-[1.20rem]">
                    Earthquakes are powerful tremors, that are a threat to you
                    and your family. Learn how to combat them.
                  </p>
                </div>
                <nav className="px-4 lg:px-6 h-14 flex items-center gap-4 transition-all ease-in delay-1000 hover:underline-offset-8 bg-primary text-primary-foreground">
                  <Link
                    href="#about"
                    className="text-sm font-medium hover:underline underline-offset-4"
                    prefetch={false}
                  >
                    About
                  </Link>
                  <Link
                    href="#prepare"
                    className="text-sm font-medium hover:underline underline-offset-4"
                    prefetch={false}
                  >
                    Prepare
                  </Link>
                  <Link
                    href="#worst-cases"
                    className="text-sm font-medium hover:underline underline-offset-4"
                    prefetch={false}
                  >
                    Worst Cases
                  </Link>
                  <Link
                    href="#impact"
                    className="text-sm font-medium hover:underline underline-offset-4"
                    prefetch={false}
                  >
                    Impact
                  </Link>
                </nav>
              </div>
              <img
                src="https://c1.wallpaperflare.com/preview/418/167/736/earthquake-rubble-collapse-disaster.jpg"
                width="550"
                height="550"
                alt="Hurricane"
                className="mx-auto aspect-video overflow-hidden rounded-[120px] object-contain sm:w-full lg:order-last lg:aspect-square"
              />
            </div>
          </div>
        </section>
        <section id="about" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                    What is an Earthquake?
                  </h2>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                    An earthquake is a sudden and violent shaking of the ground,
                    caused by movements within the earth&apos;s crust or volcanic
                    activity. Earthquakes can cause significant damage to
                    buildings, infrastructure, and communities, as well as
                    injuries and loss of life.
                  </p>
                </div>
              </div>
              <img
                src="https://c1.wallpaperflare.com/preview/682/26/477/earthquake-rubble-collapse-disaster.jpg"
                width="550"
                height="310"
                alt="Hurricane Diagram"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>
        <section
          id="prepare"
          className="w-full py-12 md:py-24 lg:py-32 bg-muted"
        >
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <img
                src="https://c1.wallpaperflare.com/preview/485/718/551/china-earthquake-photos-people.jpg"
                width="550"
                height="310"
                alt="Preparing for a Hurricane"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
              <div className="flex justify-center space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                    How to Prepare for an Earthquake
                  </h2>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                    To protect yourself and your family during an earthquake, it
                    is essential to be prepared. Here are some steps you can
                    take to get ready:
                  </p>
                  <ul className="grid gap-2 text-muted-foreground">
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Secure heavy items that could fall and cause injury
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Hide under a sturdy table or desk during shaking.
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Prepare an emergency kit with food, water, and essential
                      supplies
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Have a plan for where to go if you need to evacuate
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Stay informed about earthquake risks and warnings(keep a
                      radio)
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Practice earthquake drills with your family
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="worst-cases" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl text-center">
                    Worst Cases of Earthquakes
                  </h2>
                  <p className="sm:max-w-[600px] lg:max-w-[1280px] text-center text-muted-foreground sm:text-base md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                    Earthquakes have caused some of the deadliest natural
                    disasters in history. Here are some of the worst cases of
                    earthquakes in recorded history:
                  </p>
                </div>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Sl No.</TableHead>
                      <TableHead>Name</TableHead>
                      <TableHead>Date</TableHead>
                      <TableHead>Casualty</TableHead>
                      <TableHead>Max Magnitude</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell>1</TableCell>
                      <TableCell>2001 Bhuj Earthquake</TableCell>
                      <TableCell>January 2001</TableCell>
                      <TableCell>20,023 deaths</TableCell>
                      <TableCell>7.6 Mw</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>2</TableCell>
                      <TableCell>2005 Kashmir Earthquake</TableCell>
                      <TableCell>October 2005</TableCell>
                      <TableCell>86,000 - 87,351 deaths</TableCell>
                      <TableCell>6.4 Mw</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>3</TableCell>
                      <TableCell>1993 Latur Earthquake</TableCell>
                      <TableCell>September 1993</TableCell>
                      <TableCell>9,748+ deaths</TableCell>
                      <TableCell>6.2 Mw</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>4</TableCell>
                      <TableCell>1803 Garhwal Earthquake</TableCell>
                      <TableCell>September 1803</TableCell>
                      <TableCell>200-300 deaths</TableCell>
                      <TableCell>(7.8 ± 0.2) Mw</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>5</TableCell>
                      <TableCell>2011 Sikkim Earthquake</TableCell>
                      <TableCell>September 2011</TableCell>
                      <TableCell>111+ deaths</TableCell>
                      <TableCell>
                        6.9 Mw(
                        <span className="text-alert">costliest</span>)
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
            </div>
          </div>
        </section>
        <section id="impact" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                    The Potential Impact of Earthquakes
                  </h2>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                    Earthquakes are no doubt, one of the most destructive
                    natural disasters. Capable of causing widespread damage and
                    devastation. Here are some of the potential impacts of
                    earthquakes:
                  </p>
                </div>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Impact</TableHead>
                      <TableHead>Worst-Case Scenario</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell>Infrastructure</TableCell>
                      <TableCell>
                        Collapsed buildings, bridges, and roads, leading to
                        widespread destruction and loss of services.
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Finances</TableCell>
                      <TableCell>
                        Billions of dollars in damages to homes, businesses, and
                        public infrastructure.
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Human Life</TableCell>
                      <TableCell>
                        Thousands of deaths and injuries, with long-term
                        physical and mental health impacts.
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
              <img
                src="https://c1.wallpaperflare.com/preview/448/230/432/earthquake-rubble-collapse-disaster.jpg"
                width="550"
                height="310"
                alt="Hurricane Damage"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
