/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5MmQ0CPLDoA
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 * Component has been modified to tailor towards d-info project
 */

import Link from "next/link";
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
  TableBody,
  TableCell,
} from "@/components/ui/table";
import CheckIcon from "../icons/CheckIcon";

export function FloodInfo() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-primary text-primary-foreground">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col-reverse justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-2xl font-bold tracking-tighter sm:text-5xl xl:text-5xl/none">
                    Preparing for Floods
                  </h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-[1.20rem]">
                    Floods are an overflow of water that submerges land that is
                    usually dry. Learn how you can prepare for such a threat.
                  </p>
                </div>
                <nav className="px-4 lg:px-6 h-14 flex items-center gap-4 transition-all ease-in delay-1000 hover:underline-offset-8 bg-primary text-primary-foreground">
                  <Link
                    href="#about"
                    className="text-sm font-medium hover:underline underline-offset-4"
                    prefetch={false}
                  >
                    About
                  </Link>
                  <Link
                    href="#prepare"
                    className="text-sm font-medium hover:underline underline-offset-4"
                    prefetch={false}
                  >
                    Prepare
                  </Link>
                  <Link
                    href="#worst-cases"
                    className="text-sm font-medium hover:underline underline-offset-4"
                    prefetch={false}
                  >
                    Worst Cases
                  </Link>
                  <Link
                    href="#impact"
                    className="text-sm font-medium hover:underline underline-offset-4"
                    prefetch={false}
                  >
                    Impact
                  </Link>
                </nav>
              </div>
              <img
                src="https://c1.wallpaperflare.com/preview/942/462/435/hurricane-katrina-flooding-new-orleans-after-hurricane-katrina.jpg"
                width="550"
                height="550"
                alt="Hurricane"
                className="mx-auto aspect-video overflow-hidden rounded-[120px] object-contain sm:w-full lg:order-last lg:aspect-square"
              />
            </div>
          </div>
        </section>
        <section id="about" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                    What is a flood?
                  </h2>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                    A flood is an overflow of water that submerges land that is
                    usually dry. It can be caused by heavy rainfall, melting
                    snow, or dam failure. Floods can cause significant damage to
                    infrastructure, homes, and the environment, and can also
                    pose a threat to human life and safety. It is important to
                    be prepared and take necessary precautions in flood-prone
                    areas.
                  </p>
                </div>
              </div>
              <img
                src="https://c4.wallpaperflare.com/wallpaper/214/310/570/flood-wallpaper-preview.jpg"
                width="550"
                height="310"
                alt="Hurricane Diagram"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>
        <section
          id="prepare"
          className="w-full py-12 md:py-24 lg:py-32 bg-muted"
        >
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <img
                src="https://c1.wallpaperflare.com/preview/626/964/839/high-water-road-gone-down-damage.jpg"
                width="550"
                height="310"
                alt="Preparing for a Hurricane"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
              <div className="flex justify-center space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                    How to Prepare for a Flood
                  </h2>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                    Floods are devastating, there are many things that can and
                    will go wrong if you are underprepared. Don&apos;t worry, we
                    are here to help!
                  </p>
                  <ul className="grid gap-2 text-muted-foreground">
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Understand the dangers you may face. Learn about the types
                      of flooding.
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Know your home and community&apos;s flood risk
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Avoid fallen power lines, poles, and wires.
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Prepare an emergency kit with food, water, and essential
                      supplies
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Stay away from floodwaters. They might contain hazards
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Stay informed about flash flood warnings(keep a radio)
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Contact Disaster Distress Helpline (
                      <span className="text-alert">+919711077372</span>)
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="worst-cases" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl text-center">
                    Worst Cases of Floods
                  </h2>
                  <p className="sm:max-w-[600px] lg:max-w-[1280px] text-center text-muted-foreground sm:text-base md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                    Floods have caused some of the most devastating natural
                    disasters in history. Here are some of the worst cases of
                    floods in India:
                  </p>
                </div>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Sl No.</TableHead>
                      <TableHead>Name</TableHead>
                      <TableHead>Date</TableHead>
                      <TableHead>Casualty</TableHead>
                      <TableHead>Cost</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell>1</TableCell>
                      <TableCell>2013 North Indian Floods</TableCell>
                      <TableCell>June 2013</TableCell>
                      <TableCell>6,054 deaths</TableCell>
                      <TableCell>50,000 crores</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>2</TableCell>
                      <TableCell>2008 Kosi Floods</TableCell>
                      <TableCell>August 2008</TableCell>
                      <TableCell>434+ deaths</TableCell>
                      <TableCell>8,000 - 9,900 crores</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>3</TableCell>
                      <TableCell>1978 Delhi Floods</TableCell>
                      <TableCell>September 1978</TableCell>
                      <TableCell>100+ deaths</TableCell>
                      <TableCell>
                        409 crores(adjusted to 1978 USD-INR)
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>4</TableCell>
                      <TableCell>NULL</TableCell>
                      <TableCell>NULL</TableCell>
                      <TableCell>NULL</TableCell>
                      <TableCell>NULL</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>5</TableCell>
                      <TableCell>NULL</TableCell>
                      <TableCell>NULL</TableCell>
                      <TableCell>NULL</TableCell>
                      <TableCell>NULL</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
            </div>
          </div>
        </section>
        <section id="impact" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                    The Potential Impact of Floods
                  </h2>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                    Floods while may seem harmless, can cause significant
                    damage. Damages are but not limited to you, your family,
                    your community and your nation. Here are some of the potential impacts of floods:
                  </p>
                </div>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Impact</TableHead>
                      <TableHead>Worst-Case Scenario</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell>Infrastructure</TableCell>
                      <TableCell>
                        Collapsed buildings, bridges, and roads, leading to
                        widespread destruction and loss of services.
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Finances</TableCell>
                      <TableCell>
                        Billions of dollars in damages to homes, businesses, and
                        public infrastructure.
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Human Life</TableCell>
                      <TableCell>
                        Mass displacement, instability, and loss of life.
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
              <img
                src="https://c1.wallpaperflare.com/preview/369/104/1014/flood-boys-rowing-water.jpg"
                width="550"
                height="310"
                alt="Hurricane Damage"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
