/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5MmQ0CPLDoA
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 * Component has been modified to tailor towards d-info project
 */

import Link from "next/link";
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
  TableBody,
  TableCell,
} from "@/components/ui/table";
import CheckIcon from "../icons/CheckIcon";

export function TyphoonInfo() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-primary text-primary-foreground">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col-reverse justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Preparing for Typhoons
                  </h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                    Typhoons are powerful storms that can cause widespread
                    destruction. Learn how to prepare and stay safe.
                  </p>
                </div>
                <nav className="px-4 lg:px-6 h-14 flex items-center gap-4 transition-all ease-in delay-1000 hover:underline-offset-8 bg-primary text-primary-foreground">
                  <Link
                    href="#about"
                    className="text-sm font-medium hover:underline underline-offset-4"
                    prefetch={false}
                  >
                    About
                  </Link>
                  <Link
                    href="#prepare"
                    className="text-sm font-medium hover:underline underline-offset-4"
                    prefetch={false}
                  >
                    Prepare
                  </Link>
                  <Link
                    href="#worst-cases"
                    className="text-sm font-medium hover:underline underline-offset-4"
                    prefetch={false}
                  >
                    Worst Cases
                  </Link>
                  <Link
                    href="#impact"
                    className="text-sm font-medium hover:underline underline-offset-4"
                    prefetch={false}
                  >
                    Impact
                  </Link>
                </nav>
              </div>
              <img
                src="https://c4.wallpaperflare.com/wallpaper/491/775/713/nature-landscape-tornado-new-mexico-wallpaper-preview.jpg"
                width="550"
                height="550"
                alt="Hurricane"
                className="mx-auto aspect-video overflow-hidden rounded-[120px] object-contain sm:w-full lg:order-last lg:aspect-square"
              />
            </div>
          </div>
        </section>
        <section id="about" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                    What is a Typhoon?
                  </h2>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                    A typhoon is a large, swirling storm that forms over warm
                    ocean waters. It has high-speed winds, heavy rain, and a
                    central "eye" that is relatively calm. Typhoons can cause
                    extensive damage to coastal areas and inland regions.
                  </p>
                </div>
              </div>
              <img
                src="https://c1.wallpaperflare.com/preview/879/332/42/hurricane-tropical-cyclone-typhoon-cyclone.jpg"
                width="550"
                height="310"
                alt="Hurricane Diagram"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>
        <section
          id="prepare"
          className="w-full py-12 md:py-24 lg:py-32 bg-muted"
        >
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <img
                src="https://c1.wallpaperflare.com/preview/68/855/818/winter-storm-hurricane-cyclone-typhoon.jpg"
                width="550"
                height="310"
                alt="Preparing for a Hurricane"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
              <div className="flex justify-center space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                    How to Prepare for a Typhoon
                  </h2>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                    Preparing for a typhoon can help keep you and your family
                    safe. Here are some tips:
                  </p>
                  <ul className="grid gap-2 text-muted-foreground">
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Monitor weather forecasts and evacuation orders
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Secure your home by boarding up windows and bringing
                      outdoor furniture inside
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Prepare an emergency kit with food, water, and essential
                      supplies
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Have a plan for where to go if you need to evacuate
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="worst-cases" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl text-center">
                    Worst Cases of typhoons
                  </h2>
                  <p className="sm:max-w-[600px] lg:max-w-[1280px] text-center text-muted-foreground sm:text-base md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                    Typhoons have caused devastating damage and loss of life
                    throughout history. Here are some of the worst cases:
                  </p>
                </div>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Sl No.</TableHead>
                      <TableHead>Name</TableHead>
                      <TableHead>Date</TableHead>
                      <TableHead>Casualty</TableHead>
                      <TableHead>Cost</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell>1</TableCell>
                      <TableCell>1970 Bhola Cyclone</TableCell>
                      <TableCell>November 1970</TableCell>
                      <TableCell>300,000 - 500,000</TableCell>
                      <TableCell>No data</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>2</TableCell>
                      <TableCell>1839 Coringa Cyclone</TableCell>
                      <TableCell>November 1839</TableCell>
                      <TableCell>300,000 deaths</TableCell>
                      <TableCell>
                        INR 6.48 Crore(adjusted to 1970 USD-INR)
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>3</TableCell>
                      <TableCell>1882 Bombay Cyclone</TableCell>
                      <TableCell>June 1882</TableCell>
                      <TableCell>100,000+ deaths</TableCell>
                      <TableCell>No data</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>4</TableCell>
                      <TableCell>1737 Calcutta Cyclone</TableCell>
                      <TableCell>October 1737</TableCell>
                      <TableCell>300,000 deaths</TableCell>
                      <TableCell>No data</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>5</TableCell>
                      <TableCell>1977 Andhra Pradesh Cyclone</TableCell>
                      <TableCell>November 1977</TableCell>
                      <TableCell>14,204+ deaths</TableCell>
                      <TableCell>
                        INR 6.99 Crores(adjusted to 1977 USD-INR)
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>6</TableCell>
                      <TableCell>Cyclone Amphan</TableCell>
                      <TableCell>May 2020</TableCell>
                      <TableCell>128 deaths</TableCell>
                      <TableCell>
                        $10,000 Crores(
                        <span className="text-alert">costliest</span>)
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
            </div>
          </div>
        </section>
        <section id="impact" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                    The Potential Impact of Typhoons
                  </h2>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                    Typhoons can have a devastating impact on communities,
                    causing widespread damage to infrastructure, financial
                    losses, and loss of life. Here are some potential impacts:
                  </p>
                </div>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Impact</TableHead>
                      <TableHead>Worst-Case Scenario</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell>Infrastructure</TableCell>
                      <TableCell>
                        Extensive damage to homes, businesses, roads, bridges,
                        and utilities, leading to long-term power outages and
                        disruptions.
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Finances</TableCell>
                      <TableCell>
                        Billions of dollars in property damage, business
                        interruptions, and recovery costs, leading to
                        significant economic impact.
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Human Life</TableCell>
                      <TableCell>
                        Hundreds or thousands of fatalities and injuries due to
                        high winds, flooding, and other hazards.
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
              <img
                src="https://c1.wallpaperflare.com/preview/124/302/473/tornado-destruction-joplin-missouri.jpg"
                width="550"
                height="310"
                alt="Hurricane Damage"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
